#ifndef VERSION_H
#define VERSION_H

#ifndef PRESIGN_BASE_VERSION
#define PRESIGN_BASE_VERSION "1.0"
#endif

#ifdef PRESIGN_BUILD_VERSION
#define PRESIGN_VERSION PRESIGN_BASE_VERSION " (build " PRESIGN_BUILD_VERSION ")"
#else
#define PRESIGN_VERSION PRESIGN_BASE_VERSION
#endif

#endif
