name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-debian12:
    name: Linux (Debian 12 amd64)
    runs-on: ubuntu-latest
    container:
      image: debian:12-slim
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            ca-certificates git make gcc build-essential pkg-config \
            zlib1g-dev libssl-dev curl
          update-ca-certificates || true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: make clean all
      - name: Test
        run: make check

  macos-amd64:
    name: macOS (Intel amd64)
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install coreutils via Homebrew
        run: |
          brew update || true
          brew install coreutils
      - name: Install OpenSSL via Homebrew
        run: |
          brew update || true
          brew install openssl@3 || brew install openssl
          OPENSSL_PREFIX=$(brew --prefix openssl@3 2>/dev/null || brew --prefix openssl)
          echo "OPENSSL_PREFIX=${OPENSSL_PREFIX}" >> $GITHUB_ENV
          echo "LDFLAGS=-L${OPENSSL_PREFIX}/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I${OPENSSL_PREFIX}/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=${OPENSSL_PREFIX}/lib/pkgconfig" >> $GITHUB_ENV
      - name: Build
        run: make clean all
      - name: Test
        run: make check

  macos-arm64:
    name: macOS (Apple Silicon arm64)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install coreutils via Homebrew
        run: |
          brew update || true
          brew install coreutils
      - name: Install OpenSSL via Homebrew
        run: |
          brew update || true
          brew install openssl@3 || brew install openssl
          OPENSSL_PREFIX=$(brew --prefix openssl@3 2>/dev/null || brew --prefix openssl)
          echo "OPENSSL_PREFIX=${OPENSSL_PREFIX}" >> $GITHUB_ENV
          echo "LDFLAGS=-L${OPENSSL_PREFIX}/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I${OPENSSL_PREFIX}/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=${OPENSSL_PREFIX}/lib/pkgconfig" >> $GITHUB_ENV
      - name: Build
        run: make clean all
      - name: Test
        run: make check
